[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers are now configured in next.config.mjs
# to take advantage of Next.js built-in support and CSP configuration